# This workflow will triage issues and apply a label based on the
# types: reopened or opened.

name: Label Issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: actions/github-script@v6
        with:
          script: |
            const label = "Triage";
            const issueNumber = context.issue.number;

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: [label],
            });
